---
resources:
  - name: app-source
    type: git
    icon: github
    source:
      uri: ((git-uri))
      branch: main
      # username: ((git-username))
      # password: ((git-password))

jobs:
  - name: build-and-deploy
    plan:
      - get: app-source
        trigger: true

      - task: build-app
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: maven
              tag: 3.9-eclipse-temurin-17
          inputs:
            - name: app-source
          outputs:
            - name: build-output
          run:
            path: sh
            args:
              - -exc
              - |
                cd app-source
                mvn clean package -DskipTests
                cp target/*.jar ../build-output/app.jar
                ls -la ../build-output/

      - task: prepare-manifest
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ubuntu
              tag: latest
          inputs:
            - name: app-source
            - name: build-output
          outputs:
            - name: cf-deploy
          run:
            path: sh
            args:
              - -exc
              - |
                # Copy the JAR file
                cp build-output/app.jar cf-deploy/

                # Create manifest.yml if it doesn't exist
                if [ ! -f app-source/manifest.yml ]; then
                  cat > cf-deploy/manifest.yml <<EOF
                ---
                applications:
                - name: user-api
                  memory: 1G
                  instances: 1
                  path: app.jar
                  buildpacks:
                    - java_buildpack_offline
                  env:
                    SPRING_PROFILES_ACTIVE: production
                    JBP_CONFIG_OPEN_JDK_JRE: '{ jre: { version: 17.+ } }'
                  routes:
                  - route: user-api-((cf-app-suffix)).((cf-domain))
                EOF
                else
                  cp app-source/manifest.yml cf-deploy/
                fi

                ls -la cf-deploy/

      - task: blue-green-deploy
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: governmentpaas/cf-cli
              tag: latest
          inputs:
            - name: cf-deploy
          run:
            path: sh
            args:
              - -exc
              - |
                cf api ((cf-api-endpoint))
                cf auth ((cf-username)) ((cf-password))
                cf target -o ((cf-org)) -s ((cf-space))
                cd cf-deploy

                APP_NAME="user-api"
                BLUE_APP="${APP_NAME}-blue"
                GREEN_APP="${APP_NAME}-green"
                MAIN_ROUTE="user-api-((cf-app-suffix)).((cf-domain))"
                BLUE_ROUTE="user-api-blue-((cf-app-suffix)).((cf-domain))"
                GREEN_ROUTE="user-api-green-((cf-app-suffix)).((cf-domain))"

                echo "=== Starting Blue-Green Deployment ==="

                # Determine which app is currently active
                BLUE_HAS_MAIN_ROUTE=false
                GREEN_HAS_MAIN_ROUTE=false

                if cf app $BLUE_APP > /dev/null 2>&1; then
                  echo "Blue app exists"
                  if cf app $BLUE_APP | grep -q "$MAIN_ROUTE"; then
                    BLUE_HAS_MAIN_ROUTE=true
                    echo "Blue app has main route - deploying to GREEN"
                    TARGET_APP=$GREEN_APP
                    TARGET_ROUTE=$GREEN_ROUTE
                    CURRENT_APP=$BLUE_APP
                    CURRENT_ROUTE=$BLUE_ROUTE
                  fi
                fi

                if cf app $GREEN_APP > /dev/null 2>&1; then
                  echo "Green app exists"
                  if cf app $GREEN_APP | grep -q "$MAIN_ROUTE"; then
                    GREEN_HAS_MAIN_ROUTE=true
                    echo "Green app has main route - deploying to BLUE"
                    TARGET_APP=$BLUE_APP
                    TARGET_ROUTE=$BLUE_ROUTE
                    CURRENT_APP=$GREEN_APP
                    CURRENT_ROUTE=$GREEN_ROUTE
                  fi
                fi

                # If neither has the main route, this is initial deployment
                if [ "$BLUE_HAS_MAIN_ROUTE" = false ] && [ "$GREEN_HAS_MAIN_ROUTE" = false ]; then
                  echo "Initial deployment - deploying to BLUE"
                  TARGET_APP=$BLUE_APP
                  TARGET_ROUTE=$BLUE_ROUTE
                  CURRENT_APP=""
                fi

                # Deploy new version to target color
                echo "Deploying new version to: $TARGET_APP"
                cf push $TARGET_APP -f manifest.yml --no-route

                # Wait for target app to start
                echo "Waiting for target app to be ready..."
                sleep 10

                # Verify target app is running
                if ! cf app $TARGET_APP | grep "started"; then
                  echo "ERROR: Target app failed to start"
                  cf logs $TARGET_APP --recent
                  exit 1
                fi

                # Map color-specific route to target app
                echo "Mapping color-specific route $TARGET_ROUTE to $TARGET_APP"
                cf map-route $TARGET_APP ((cf-domain)) --hostname user-api-${TARGET_APP##*-}-((cf-app-suffix))

                # Map main route to target app
                echo "Mapping main route $MAIN_ROUTE to $TARGET_APP"
                cf map-route $TARGET_APP ((cf-domain)) --hostname user-api-((cf-app-suffix))

                # Wait for routes to propagate
                sleep 5

                # Test the target app on the main route
                echo "Testing target app on main route..."
                # Add basic health check here if needed

                # If there was a current app, unmap main route from it
                if [ -n "$CURRENT_APP" ]; then
                  echo "Unmapping main route from $CURRENT_APP"
                  cf unmap-route $CURRENT_APP ((cf-domain)) --hostname user-api-((cf-app-suffix)) || echo "Route not mapped"

                  echo "Current app $CURRENT_APP is still accessible at $CURRENT_ROUTE for rollback"
                fi

                echo "=== Blue-Green Deployment Complete ==="
                echo "Active app: $TARGET_APP"
                echo "  - Main route: $MAIN_ROUTE"
                echo "  - Color route: $TARGET_ROUTE"
                if [ -n "$CURRENT_APP" ]; then
                  echo "Inactive app: $CURRENT_APP (available for rollback)"
                  echo "  - Color route: $CURRENT_ROUTE"
                fi

                cf apps | grep user-api

  - name: test-deployment
    plan:
      - get: app-source
        trigger: true
        passed: [build-and-deploy]

      - task: smoke-test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: curlimages/curl
              tag: latest
          run:
            path: sh
            args:
              - -exc
              - |
                echo "Running smoke tests..."
                sleep 10

                APP_URL="https://user-api-((cf-app-suffix)).((cf-domain))"

                # Test health endpoint
                echo "Testing $APP_URL/actuator/health"
                # curl -f $APP_URL/actuator/health || echo "Health check not available"

                # Test users endpoint
                echo "Testing $APP_URL/users"
                # curl -f $APP_URL/users

                echo "Smoke tests completed (placeholder - edit URLs when CF is configured)"
