---
resources:
  - name: app-source
    type: git
    icon: github
    source:
      uri: ((git-uri))
      branch: main
      # username: ((git-username))
      # password: ((git-password))

jobs:
  - name: build-and-deploy
    plan:
      - get: app-source
        trigger: true

      - task: build-app
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: maven
              tag: 3.9-eclipse-temurin-17
          inputs:
            - name: app-source
          outputs:
            - name: build-output
          run:
            path: sh
            args:
              - -exc
              - |
                cd app-source
                mvn clean package -DskipTests
                cp target/*.jar ../build-output/app.jar
                ls -la ../build-output/

      - task: prepare-manifest
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ubuntu
              tag: latest
          inputs:
            - name: app-source
            - name: build-output
          outputs:
            - name: cf-deploy
          run:
            path: sh
            args:
              - -exc
              - |
                # Copy the JAR file
                cp build-output/app.jar cf-deploy/

                # Create manifest.yml if it doesn't exist
                if [ ! -f app-source/manifest.yml ]; then
                  cat > cf-deploy/manifest.yml <<EOF
                ---
                applications:
                - name: user-api
                  memory: 1G
                  instances: 1
                  path: app.jar
                  buildpacks:
                    - java_buildpack_offline
                  env:
                    SPRING_PROFILES_ACTIVE: production
                    JBP_CONFIG_OPEN_JDK_JRE: '{ jre: { version: 17.+ } }'
                  routes:
                  - route: user-api-((cf-app-suffix)).((cf-domain))
                EOF
                else
                  cp app-source/manifest.yml cf-deploy/
                fi

                ls -la cf-deploy/

      - task: blue-green-deploy
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: governmentpaas/cf-cli
              tag: latest
          inputs:
            - name: cf-deploy
          run:
            path: sh
            args:
              - -exc
              - |
                cf api ((cf-api-endpoint))
                cf auth ((cf-username)) ((cf-password))
                cf target -o ((cf-org)) -s ((cf-space))
                cd cf-deploy

                APP_NAME="user-api"
                GREEN_APP="${APP_NAME}-green"
                ROUTE="user-api-((cf-app-suffix)).((cf-domain))"

                echo "=== Starting Blue-Green Deployment ==="

                # Check if the main app exists
                if cf app $APP_NAME > /dev/null 2>&1; then
                  echo "Main app $APP_NAME exists - performing blue-green deployment"
                  BLUE_EXISTS=true
                else
                  echo "Main app $APP_NAME does not exist - performing initial deployment"
                  BLUE_EXISTS=false
                fi

                # Deploy green app
                echo "Deploying green app: $GREEN_APP"
                cf push $GREEN_APP -f manifest.yml --no-route

                # Wait for green app to start
                echo "Waiting for green app to be ready..."
                sleep 10

                # Verify green app is running
                if ! cf app $GREEN_APP | grep "started"; then
                  echo "ERROR: Green app failed to start"
                  cf logs $GREEN_APP --recent
                  exit 1
                fi

                # Map the route to green app
                echo "Mapping route $ROUTE to green app"
                cf map-route $GREEN_APP ((cf-domain)) --hostname user-api-((cf-app-suffix))

                # Wait for route to propagate
                sleep 5

                # Test the green app on the shared route
                echo "Testing green app..."
                # Add basic health check here if needed

                if [ "$BLUE_EXISTS" = true ]; then
                  # Unmap route from blue app
                  echo "Unmapping route from blue app"
                  cf unmap-route $APP_NAME ((cf-domain)) --hostname user-api-((cf-app-suffix)) || echo "Route not mapped to blue app"

                  # Stop and delete the old blue app
                  echo "Stopping old blue app"
                  cf stop $APP_NAME

                  echo "Deleting old blue app"
                  cf delete $APP_NAME -f
                fi

                # Rename green to blue
                echo "Renaming green app to main app name"
                cf rename $GREEN_APP $APP_NAME

                echo "=== Blue-Green Deployment Complete ==="
                cf app $APP_NAME

  - name: test-deployment
    plan:
      - get: app-source
        trigger: true
        passed: [build-and-deploy]

      - task: smoke-test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: curlimages/curl
              tag: latest
          run:
            path: sh
            args:
              - -exc
              - |
                echo "Running smoke tests..."
                sleep 10

                APP_URL="https://user-api-((cf-app-suffix)).((cf-domain))"

                # Test health endpoint
                echo "Testing $APP_URL/actuator/health"
                # curl -f $APP_URL/actuator/health || echo "Health check not available"

                # Test users endpoint
                echo "Testing $APP_URL/users"
                # curl -f $APP_URL/users

                echo "Smoke tests completed (placeholder - edit URLs when CF is configured)"
