---
resources:
  - name: app-source
    type: git
    icon: github
    source:
      uri: ((git-uri))
      branch: main

  - name: daily-trigger
    type: time
    icon: clock-outline
    source:
      interval: 24h  # Run daily
      location: Europe/Brussels

jobs:
  - name: check-for-upgrades
    plan:
      - get: app-source
      - get: daily-trigger
        trigger: true

      - task: run-saa-and-create-pr
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: maven
              tag: 3.9-eclipse-temurin-17
          inputs:
            - name: app-source
          params:
            GIT_URI: ((git-uri))
            GIT_USERNAME: ((git-username))
            GIT_PASSWORD: ((git-password))
            GITHUB_TOKEN: ((github-token))
          run:
            path: sh
            args:
              - -exc
              - |
                # Install required tools
                apt-get update && apt-get install -y curl jq git

                # Install GitHub CLI
                curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
                echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null
                apt-get update && apt-get install -y gh

                # Install advisor CLI from repository (extract from tar)
                tar -xf app-source/ci/bin/application-advisor-cli-linux-1.5.2.tar -C /tmp
                cp /tmp/advisor /usr/local/bin/advisor
                chmod +x /usr/local/bin/advisor

                cd app-source

                # Configure git
                git config --global user.email "concourse-bot@example.com"
                git config --global user.name "Concourse SAA Bot"

                # Set up git credentials
                git remote set-url origin https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/${GIT_URI#https://github.com/}

                # Generate build config if needed
                advisor build-config get || advisor build-config generate

                # Check for upgrade plans
                echo "Checking for available upgrades..."
                advisor upgrade-plan get > upgrade-plan.txt || true

                # Check if upgrades are available
                if grep -q "No upgrade plans available" upgrade-plan.txt; then
                  echo "No upgrades available. Skipping PR creation."
                  exit 0
                fi

                echo "Upgrades available! Proceeding with upgrade and PR creation..."

                # Create a unique branch name with timestamp
                BRANCH_NAME="saa-upgrades-$(date +%Y%m%d-%H%M%S)"
                git checkout -b $BRANCH_NAME

                # Apply upgrade plan
                echo "Applying upgrade plan..."
                advisor upgrade-plan apply --non-interactive || {
                  echo "Upgrade plan application failed"
                  exit 1
                }

                # Check if there are any changes
                if git diff --quiet; then
                  echo "No changes after applying upgrades"
                  exit 0
                fi

                # Commit changes
                git add -A
                git commit -m "Apply Spring Application Advisor upgrades

                Automated upgrade applied by Spring Application Advisor.

                $(cat upgrade-plan.txt)

                🤖 Generated by Concourse SAA Pipeline"

                # Push branch
                git push origin $BRANCH_NAME

                # Create PR using GitHub CLI
                export GH_TOKEN=$GITHUB_TOKEN

                # Extract repo owner and name from git URI
                REPO_PATH=$(echo $GIT_URI | sed 's#https://github.com/##' | sed 's#.git$##')

                gh pr create \
                  --repo $REPO_PATH \
                  --base main \
                  --head $BRANCH_NAME \
                  --title "🔄 Spring Application Advisor - Automated Upgrades" \
                  --body "## Spring Application Advisor Upgrade Plan

                This PR contains automated upgrades suggested by Spring Application Advisor.

                ### Upgrade Details
                \`\`\`
                $(cat upgrade-plan.txt)
                \`\`\`

                ### What's Changed
                - Spring Boot and dependency upgrades
                - Configuration updates for compatibility
                - Code migrations if required

                ### Testing Required
                - [ ] Review upgrade plan details
                - [ ] Run tests locally
                - [ ] Verify application behavior
                - [ ] Check for breaking changes

                **Note**: This PR was automatically generated by the Concourse SAA pipeline.
                Review carefully before merging.

                ---
                🤖 Generated by Concourse SAA Pipeline on $(date)"

                echo "PR created successfully!"

  - name: check-for-advice
    plan:
      - get: app-source
      - get: daily-trigger
        trigger: true
        passed: [check-for-upgrades]

      - task: run-saa-advice
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: maven
              tag: 3.9-eclipse-temurin-17
          inputs:
            - name: app-source
          params:
            GIT_URI: ((git-uri))
            GIT_USERNAME: ((git-username))
            GIT_PASSWORD: ((git-password))
            GITHUB_TOKEN: ((github-token))
          run:
            path: sh
            args:
              - -exc
              - |
                # Install required tools
                apt-get update && apt-get install -y curl jq git

                # Install GitHub CLI
                curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
                echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null
                apt-get update && apt-get install -y gh

                # Install advisor CLI from repository (extract from tar)
                tar -xf app-source/ci/bin/application-advisor-cli-linux-1.5.2.tar -C /tmp
                cp /tmp/advisor /usr/local/bin/advisor
                chmod +x /usr/local/bin/advisor

                cd app-source

                # Configure git
                git config --global user.email "concourse-bot@example.com"
                git config --global user.name "Concourse SAA Bot"

                # Set up git credentials
                git remote set-url origin https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/${GIT_URI#https://github.com/}

                # Generate build config if needed
                advisor build-config get || advisor build-config generate

                # Check for advice
                echo "Checking for available best practice advice..."
                advisor advice list > advice-list.txt || true

                # Check if advice is available
                ADVICE_COUNT=$(grep -c "advice(s) found" advice-list.txt || echo "0")

                if [ "$ADVICE_COUNT" = "0" ] || grep -q "0 advice(s) found" advice-list.txt; then
                  echo "No advice available. Skipping PR creation."
                  exit 0
                fi

                echo "Advice available! Creating informational issue..."

                # Create an issue with advice instead of PR (since advice requires selection)
                export GH_TOKEN=$GITHUB_TOKEN
                REPO_PATH=$(echo $GIT_URI | sed 's#https://github.com/##' | sed 's#.git$##')

                # Check if similar issue already exists
                EXISTING_ISSUE=$(gh issue list --repo $REPO_PATH --state open --label "saa-advice" --limit 1 --json number --jq '.[0].number' || echo "")

                if [ -n "$EXISTING_ISSUE" ]; then
                  echo "Advice issue already exists (#$EXISTING_ISSUE). Updating..."
                  gh issue comment $EXISTING_ISSUE --repo $REPO_PATH --body "Updated on $(date):

                \`\`\`
                $(cat advice-list.txt)
                \`\`\`"
                else
                  echo "Creating new advice issue..."
                  gh issue create \
                    --repo $REPO_PATH \
                    --title "💡 Spring Application Advisor - Best Practice Recommendations" \
                    --label "saa-advice" \
                    --body "## Spring Application Advisor Recommendations

                Spring Application Advisor has identified best practice improvements for this project.

                ### Available Advice
                \`\`\`
                $(cat advice-list.txt)
                \`\`\`

                ### How to Apply
                To apply any of these recommendations, run:
                \`\`\`bash
                advisor advice apply <advice-name>
                \`\`\`

                For example:
                - \`advisor advice apply java-21\` - Upgrade to Java 21
                - \`advisor advice apply spring-governance-starter\` - Add security governance
                - \`advisor advice apply tanzu\` - Generate Tanzu manifest

                ---
                🤖 Auto-generated by Concourse SAA Pipeline on $(date)
                This issue will be updated daily if recommendations change."
                fi

                echo "Advice notification complete!"
